version: "3.8"

services:
  api:
    image: dahern/swypify:latest
    depends_on:
      - db
    ports:
      - "80:8000"
    env_file:
      - .env.prod

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
